### ISSUE TITLE
Support for pinning minor version, clean state tests

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack-formulas/elasticsearch-formula#30]
Is it just me or does `state.highstate test=True` always say the package will be upgraded even when it's up to date?

          ID: elasticsearch_pkg
    Function: pkg.installed
        Name: elasticsearch
      Result: None
     Comment: The following packages would be installed/updated: elasticsearch=5.*
     Started: 23:23:50.533340
    Duration: 1.268 ms
     Changes:

What do you think about adding support for pinning the minor version so test=True applies cleanly?  I'd be happy to open a PR... also let me know if you have any other solutions in mind.

**Comment by blbradley** [comment]
I don't about much about the behavior of highstate test mode.

I see the need for this. Elasticsearch has the problem of different package repo URLs across different versions. Right now, `major_version` doesn't do more than change the repo URL for ES 2 or 5. A better solution would be to allow users to modify a `version` pillar and check for the major version from it.

**Comment by simonclausen** [comment]
It would be great to have this.

I've also run into the issue of an unintended upgrade of a node breaking things, because versions change. This also applies to rolling out new nodes and adding them to an existing cluster: the install currently just grabs the newest version from the repo, resulting in possible differences in version between the new node and the old nodes in the cluster.

This may require a different issue and discussion, but when we get into controlling specific versions, we touch on the subject of upgrades. What would be the best way to handle an upgrade of Elasticsearch and plugins on a node, when the version in pillar changes between highstate?

**Comment by cmclaughlin** [comment]
@simonclausen I handle upgrades by booting an entirely new cluster, then indexing my data to insert into the new cluster.  This won't work for everyone... especially not huge data sets.  But it's great if it works for your use case.

**Comment by simonclausen** [comment]
@cmclaughlin yes, that's probably the best way to handle it, if possible.

But when you have huge amounts of data sitting in Elasticsearch the easier way out is to upgrade in place over setting up a new cluster and loading existing data from snapshots.

Should I open a separate issue for that talk?

**Comment by cmclaughlin** [comment]
Yeah I guess opening a new issue would be good... I'm not a maintainer, just an occasional committer :)

**Comment by blbradley** [comment]
Closed by #31.
